#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_EC2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Examen_ProyectoEscuela")]
	public partial class conexDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAlumnos(Alumnos instance);
    partial void UpdateAlumnos(Alumnos instance);
    partial void DeleteAlumnos(Alumnos instance);
    partial void InsertCargas_Alumnos(Cargas_Alumnos instance);
    partial void UpdateCargas_Alumnos(Cargas_Alumnos instance);
    partial void DeleteCargas_Alumnos(Cargas_Alumnos instance);
    partial void InsertCargas_Docentes(Cargas_Docentes instance);
    partial void UpdateCargas_Docentes(Cargas_Docentes instance);
    partial void DeleteCargas_Docentes(Cargas_Docentes instance);
    partial void InsertCarreras(Carreras instance);
    partial void UpdateCarreras(Carreras instance);
    partial void DeleteCarreras(Carreras instance);
    partial void InsertMaestros(Maestros instance);
    partial void UpdateMaestros(Maestros instance);
    partial void DeleteMaestros(Maestros instance);
    partial void InsertMaterias(Materias instance);
    partial void UpdateMaterias(Materias instance);
    partial void DeleteMaterias(Materias instance);
    partial void InsertUsuarios_del_sistema(Usuarios_del_sistema instance);
    partial void UpdateUsuarios_del_sistema(Usuarios_del_sistema instance);
    partial void DeleteUsuarios_del_sistema(Usuarios_del_sistema instance);
    #endregion
		
		public conexDataContext() : 
				base(global::Examen_EC2.Properties.Settings.Default.Examen_ProyectoEscuelaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public conexDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Alumnos> Alumnos
		{
			get
			{
				return this.GetTable<Alumnos>();
			}
		}
		
		public System.Data.Linq.Table<Cargas_Alumnos> Cargas_Alumnos
		{
			get
			{
				return this.GetTable<Cargas_Alumnos>();
			}
		}
		
		public System.Data.Linq.Table<Cargas_Docentes> Cargas_Docentes
		{
			get
			{
				return this.GetTable<Cargas_Docentes>();
			}
		}
		
		public System.Data.Linq.Table<Carreras> Carreras
		{
			get
			{
				return this.GetTable<Carreras>();
			}
		}
		
		public System.Data.Linq.Table<Maestros> Maestros
		{
			get
			{
				return this.GetTable<Maestros>();
			}
		}
		
		public System.Data.Linq.Table<Materias> Materias
		{
			get
			{
				return this.GetTable<Materias>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios_del_sistema> Usuarios_del_sistema
		{
			get
			{
				return this.GetTable<Usuarios_del_sistema>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarCargasAlumnos")]
		public ISingleResult<MostrarCargasAlumnosResult> MostrarCargasAlumnos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MostrarCargasAlumnosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarCargasDocentes")]
		public ISingleResult<MostrarCargasDocentesResult> MostrarCargasDocentes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MostrarCargasDocentesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Login")]
		public ISingleResult<LoginResult> Login([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(1)")] System.Nullable<char> usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(1)")] System.Nullable<char> pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, pass);
			return ((ISingleResult<LoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LoginPass")]
		public ISingleResult<LoginPassResult> LoginPass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(1)")] System.Nullable<char> pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pass);
			return ((ISingleResult<LoginPassResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LoginUsuario")]
		public ISingleResult<LoginUsuarioResult> LoginUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(1)")] System.Nullable<char> usu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usu);
			return ((ISingleResult<LoginUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarNombreCarrera_Por_IdAlumno")]
		public ISingleResult<MostrarNombreCarrera_Por_IdAlumnoResult> MostrarNombreCarrera_Por_IdAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idAlumno)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idAlumno);
			return ((ISingleResult<MostrarNombreCarrera_Por_IdAlumnoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarAlumnos")]
		public ISingleResult<MostrarAlumnosResult> MostrarAlumnos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MostrarAlumnosResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alumnos")]
	public partial class Alumnos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Alumno;
		
		private string _Nombre;
		
		private int _Carrera;
		
		private EntityRef<Carreras> _Carreras;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AlumnoChanging(int value);
    partial void OnID_AlumnoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCarreraChanging(int value);
    partial void OnCarreraChanged();
    #endregion
		
		public Alumnos()
		{
			this._Carreras = default(EntityRef<Carreras>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Alumno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Alumno
		{
			get
			{
				return this._ID_Alumno;
			}
			set
			{
				if ((this._ID_Alumno != value))
				{
					this.OnID_AlumnoChanging(value);
					this.SendPropertyChanging();
					this._ID_Alumno = value;
					this.SendPropertyChanged("ID_Alumno");
					this.OnID_AlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="Int NOT NULL")]
		public int Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					if (this._Carreras.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarreraChanging(value);
					this.SendPropertyChanging();
					this._Carrera = value;
					this.SendPropertyChanged("Carrera");
					this.OnCarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carreras_Alumnos", Storage="_Carreras", ThisKey="Carrera", OtherKey="ID_Carrera", IsForeignKey=true)]
		public Carreras Carreras
		{
			get
			{
				return this._Carreras.Entity;
			}
			set
			{
				Carreras previousValue = this._Carreras.Entity;
				if (((previousValue != value) 
							|| (this._Carreras.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carreras.Entity = null;
						previousValue.Alumnos.Remove(this);
					}
					this._Carreras.Entity = value;
					if ((value != null))
					{
						value.Alumnos.Add(this);
						this._Carrera = value.ID_Carrera;
					}
					else
					{
						this._Carrera = default(int);
					}
					this.SendPropertyChanged("Carreras");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Cargas Alumnos]")]
	public partial class Cargas_Alumnos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Alumno;
		
		private int _Nombre;
		
		private int _Carrera;
		
		private int _Materia;
		
		private int _Profesor;
		
		private EntityRef<Carreras> _Carreras;
		
		private EntityRef<Maestros> _Maestros;
		
		private EntityRef<Materias> _Materias;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AlumnoChanging(int value);
    partial void OnID_AlumnoChanged();
    partial void OnNombreChanging(int value);
    partial void OnNombreChanged();
    partial void OnCarreraChanging(int value);
    partial void OnCarreraChanged();
    partial void OnMateriaChanging(int value);
    partial void OnMateriaChanged();
    partial void OnProfesorChanging(int value);
    partial void OnProfesorChanged();
    #endregion
		
		public Cargas_Alumnos()
		{
			this._Carreras = default(EntityRef<Carreras>);
			this._Maestros = default(EntityRef<Maestros>);
			this._Materias = default(EntityRef<Materias>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Alumno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Alumno
		{
			get
			{
				return this._ID_Alumno;
			}
			set
			{
				if ((this._ID_Alumno != value))
				{
					this.OnID_AlumnoChanging(value);
					this.SendPropertyChanging();
					this._ID_Alumno = value;
					this.SendPropertyChanged("ID_Alumno");
					this.OnID_AlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="Int NOT NULL")]
		public int Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="Int NOT NULL")]
		public int Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					if (this._Carreras.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarreraChanging(value);
					this.SendPropertyChanging();
					this._Carrera = value;
					this.SendPropertyChanged("Carrera");
					this.OnCarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materia", DbType="Int NOT NULL")]
		public int Materia
		{
			get
			{
				return this._Materia;
			}
			set
			{
				if ((this._Materia != value))
				{
					if (this._Materias.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMateriaChanging(value);
					this.SendPropertyChanging();
					this._Materia = value;
					this.SendPropertyChanged("Materia");
					this.OnMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesor", DbType="Int NOT NULL")]
		public int Profesor
		{
			get
			{
				return this._Profesor;
			}
			set
			{
				if ((this._Profesor != value))
				{
					if (this._Maestros.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProfesorChanging(value);
					this.SendPropertyChanging();
					this._Profesor = value;
					this.SendPropertyChanged("Profesor");
					this.OnProfesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carreras_Cargas_Alumnos", Storage="_Carreras", ThisKey="Carrera", OtherKey="ID_Carrera", IsForeignKey=true)]
		public Carreras Carreras
		{
			get
			{
				return this._Carreras.Entity;
			}
			set
			{
				Carreras previousValue = this._Carreras.Entity;
				if (((previousValue != value) 
							|| (this._Carreras.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carreras.Entity = null;
						previousValue.Cargas_Alumnos.Remove(this);
					}
					this._Carreras.Entity = value;
					if ((value != null))
					{
						value.Cargas_Alumnos.Add(this);
						this._Carrera = value.ID_Carrera;
					}
					else
					{
						this._Carrera = default(int);
					}
					this.SendPropertyChanged("Carreras");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Maestros_Cargas_Alumnos", Storage="_Maestros", ThisKey="Profesor", OtherKey="ID_Maestros", IsForeignKey=true)]
		public Maestros Maestros
		{
			get
			{
				return this._Maestros.Entity;
			}
			set
			{
				Maestros previousValue = this._Maestros.Entity;
				if (((previousValue != value) 
							|| (this._Maestros.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Maestros.Entity = null;
						previousValue.Cargas_Alumnos.Remove(this);
					}
					this._Maestros.Entity = value;
					if ((value != null))
					{
						value.Cargas_Alumnos.Add(this);
						this._Profesor = value.ID_Maestros;
					}
					else
					{
						this._Profesor = default(int);
					}
					this.SendPropertyChanged("Maestros");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Materias_Cargas_Alumnos", Storage="_Materias", ThisKey="Materia", OtherKey="ID_Materia", IsForeignKey=true)]
		public Materias Materias
		{
			get
			{
				return this._Materias.Entity;
			}
			set
			{
				Materias previousValue = this._Materias.Entity;
				if (((previousValue != value) 
							|| (this._Materias.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Materias.Entity = null;
						previousValue.Cargas_Alumnos.Remove(this);
					}
					this._Materias.Entity = value;
					if ((value != null))
					{
						value.Cargas_Alumnos.Add(this);
						this._Materia = value.ID_Materia;
					}
					else
					{
						this._Materia = default(int);
					}
					this.SendPropertyChanged("Materias");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Cargas Docentes]")]
	public partial class Cargas_Docentes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Docente;
		
		private int _Nombre;
		
		private System.Nullable<int> _Carrera;
		
		private System.Nullable<int> _Materia;
		
		private EntityRef<Carreras> _Carreras;
		
		private EntityRef<Maestros> _Maestros;
		
		private EntityRef<Materias> _Materias;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DocenteChanging(int value);
    partial void OnID_DocenteChanged();
    partial void OnNombreChanging(int value);
    partial void OnNombreChanged();
    partial void OnCarreraChanging(System.Nullable<int> value);
    partial void OnCarreraChanged();
    partial void OnMateriaChanging(System.Nullable<int> value);
    partial void OnMateriaChanged();
    #endregion
		
		public Cargas_Docentes()
		{
			this._Carreras = default(EntityRef<Carreras>);
			this._Maestros = default(EntityRef<Maestros>);
			this._Materias = default(EntityRef<Materias>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Docente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Docente
		{
			get
			{
				return this._ID_Docente;
			}
			set
			{
				if ((this._ID_Docente != value))
				{
					this.OnID_DocenteChanging(value);
					this.SendPropertyChanging();
					this._ID_Docente = value;
					this.SendPropertyChanged("ID_Docente");
					this.OnID_DocenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="Int NOT NULL")]
		public int Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					if (this._Maestros.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="Int")]
		public System.Nullable<int> Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					if (this._Carreras.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarreraChanging(value);
					this.SendPropertyChanging();
					this._Carrera = value;
					this.SendPropertyChanged("Carrera");
					this.OnCarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materia", DbType="Int")]
		public System.Nullable<int> Materia
		{
			get
			{
				return this._Materia;
			}
			set
			{
				if ((this._Materia != value))
				{
					if (this._Materias.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMateriaChanging(value);
					this.SendPropertyChanging();
					this._Materia = value;
					this.SendPropertyChanged("Materia");
					this.OnMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carreras_Cargas_Docentes", Storage="_Carreras", ThisKey="Carrera", OtherKey="ID_Carrera", IsForeignKey=true)]
		public Carreras Carreras
		{
			get
			{
				return this._Carreras.Entity;
			}
			set
			{
				Carreras previousValue = this._Carreras.Entity;
				if (((previousValue != value) 
							|| (this._Carreras.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carreras.Entity = null;
						previousValue.Cargas_Docentes.Remove(this);
					}
					this._Carreras.Entity = value;
					if ((value != null))
					{
						value.Cargas_Docentes.Add(this);
						this._Carrera = value.ID_Carrera;
					}
					else
					{
						this._Carrera = default(Nullable<int>);
					}
					this.SendPropertyChanged("Carreras");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Maestros_Cargas_Docentes", Storage="_Maestros", ThisKey="Nombre", OtherKey="ID_Maestros", IsForeignKey=true)]
		public Maestros Maestros
		{
			get
			{
				return this._Maestros.Entity;
			}
			set
			{
				Maestros previousValue = this._Maestros.Entity;
				if (((previousValue != value) 
							|| (this._Maestros.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Maestros.Entity = null;
						previousValue.Cargas_Docentes.Remove(this);
					}
					this._Maestros.Entity = value;
					if ((value != null))
					{
						value.Cargas_Docentes.Add(this);
						this._Nombre = value.ID_Maestros;
					}
					else
					{
						this._Nombre = default(int);
					}
					this.SendPropertyChanged("Maestros");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Materias_Cargas_Docentes", Storage="_Materias", ThisKey="Materia", OtherKey="ID_Materia", IsForeignKey=true)]
		public Materias Materias
		{
			get
			{
				return this._Materias.Entity;
			}
			set
			{
				Materias previousValue = this._Materias.Entity;
				if (((previousValue != value) 
							|| (this._Materias.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Materias.Entity = null;
						previousValue.Cargas_Docentes.Remove(this);
					}
					this._Materias.Entity = value;
					if ((value != null))
					{
						value.Cargas_Docentes.Add(this);
						this._Materia = value.ID_Materia;
					}
					else
					{
						this._Materia = default(Nullable<int>);
					}
					this.SendPropertyChanged("Materias");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Carreras")]
	public partial class Carreras : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Carrera;
		
		private string _Nombre;
		
		private EntitySet<Alumnos> _Alumnos;
		
		private EntitySet<Cargas_Alumnos> _Cargas_Alumnos;
		
		private EntitySet<Cargas_Docentes> _Cargas_Docentes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CarreraChanging(int value);
    partial void OnID_CarreraChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Carreras()
		{
			this._Alumnos = new EntitySet<Alumnos>(new Action<Alumnos>(this.attach_Alumnos), new Action<Alumnos>(this.detach_Alumnos));
			this._Cargas_Alumnos = new EntitySet<Cargas_Alumnos>(new Action<Cargas_Alumnos>(this.attach_Cargas_Alumnos), new Action<Cargas_Alumnos>(this.detach_Cargas_Alumnos));
			this._Cargas_Docentes = new EntitySet<Cargas_Docentes>(new Action<Cargas_Docentes>(this.attach_Cargas_Docentes), new Action<Cargas_Docentes>(this.detach_Cargas_Docentes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Carrera", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Carrera
		{
			get
			{
				return this._ID_Carrera;
			}
			set
			{
				if ((this._ID_Carrera != value))
				{
					this.OnID_CarreraChanging(value);
					this.SendPropertyChanging();
					this._ID_Carrera = value;
					this.SendPropertyChanged("ID_Carrera");
					this.OnID_CarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carreras_Alumnos", Storage="_Alumnos", ThisKey="ID_Carrera", OtherKey="Carrera")]
		public EntitySet<Alumnos> Alumnos
		{
			get
			{
				return this._Alumnos;
			}
			set
			{
				this._Alumnos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carreras_Cargas_Alumnos", Storage="_Cargas_Alumnos", ThisKey="ID_Carrera", OtherKey="Carrera")]
		public EntitySet<Cargas_Alumnos> Cargas_Alumnos
		{
			get
			{
				return this._Cargas_Alumnos;
			}
			set
			{
				this._Cargas_Alumnos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carreras_Cargas_Docentes", Storage="_Cargas_Docentes", ThisKey="ID_Carrera", OtherKey="Carrera")]
		public EntitySet<Cargas_Docentes> Cargas_Docentes
		{
			get
			{
				return this._Cargas_Docentes;
			}
			set
			{
				this._Cargas_Docentes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alumnos(Alumnos entity)
		{
			this.SendPropertyChanging();
			entity.Carreras = this;
		}
		
		private void detach_Alumnos(Alumnos entity)
		{
			this.SendPropertyChanging();
			entity.Carreras = null;
		}
		
		private void attach_Cargas_Alumnos(Cargas_Alumnos entity)
		{
			this.SendPropertyChanging();
			entity.Carreras = this;
		}
		
		private void detach_Cargas_Alumnos(Cargas_Alumnos entity)
		{
			this.SendPropertyChanging();
			entity.Carreras = null;
		}
		
		private void attach_Cargas_Docentes(Cargas_Docentes entity)
		{
			this.SendPropertyChanging();
			entity.Carreras = this;
		}
		
		private void detach_Cargas_Docentes(Cargas_Docentes entity)
		{
			this.SendPropertyChanging();
			entity.Carreras = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Maestros")]
	public partial class Maestros : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Maestros;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private EntitySet<Cargas_Alumnos> _Cargas_Alumnos;
		
		private EntitySet<Cargas_Docentes> _Cargas_Docentes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MaestrosChanging(int value);
    partial void OnID_MaestrosChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    #endregion
		
		public Maestros()
		{
			this._Cargas_Alumnos = new EntitySet<Cargas_Alumnos>(new Action<Cargas_Alumnos>(this.attach_Cargas_Alumnos), new Action<Cargas_Alumnos>(this.detach_Cargas_Alumnos));
			this._Cargas_Docentes = new EntitySet<Cargas_Docentes>(new Action<Cargas_Docentes>(this.attach_Cargas_Docentes), new Action<Cargas_Docentes>(this.detach_Cargas_Docentes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Maestros", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Maestros
		{
			get
			{
				return this._ID_Maestros;
			}
			set
			{
				if ((this._ID_Maestros != value))
				{
					this.OnID_MaestrosChanging(value);
					this.SendPropertyChanging();
					this._ID_Maestros = value;
					this.SendPropertyChanged("ID_Maestros");
					this.OnID_MaestrosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Maestros_Cargas_Alumnos", Storage="_Cargas_Alumnos", ThisKey="ID_Maestros", OtherKey="Profesor")]
		public EntitySet<Cargas_Alumnos> Cargas_Alumnos
		{
			get
			{
				return this._Cargas_Alumnos;
			}
			set
			{
				this._Cargas_Alumnos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Maestros_Cargas_Docentes", Storage="_Cargas_Docentes", ThisKey="ID_Maestros", OtherKey="Nombre")]
		public EntitySet<Cargas_Docentes> Cargas_Docentes
		{
			get
			{
				return this._Cargas_Docentes;
			}
			set
			{
				this._Cargas_Docentes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cargas_Alumnos(Cargas_Alumnos entity)
		{
			this.SendPropertyChanging();
			entity.Maestros = this;
		}
		
		private void detach_Cargas_Alumnos(Cargas_Alumnos entity)
		{
			this.SendPropertyChanging();
			entity.Maestros = null;
		}
		
		private void attach_Cargas_Docentes(Cargas_Docentes entity)
		{
			this.SendPropertyChanging();
			entity.Maestros = this;
		}
		
		private void detach_Cargas_Docentes(Cargas_Docentes entity)
		{
			this.SendPropertyChanging();
			entity.Maestros = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Materias")]
	public partial class Materias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Materia;
		
		private string _Nombre;
		
		private EntitySet<Cargas_Alumnos> _Cargas_Alumnos;
		
		private EntitySet<Cargas_Docentes> _Cargas_Docentes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MateriaChanging(int value);
    partial void OnID_MateriaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Materias()
		{
			this._Cargas_Alumnos = new EntitySet<Cargas_Alumnos>(new Action<Cargas_Alumnos>(this.attach_Cargas_Alumnos), new Action<Cargas_Alumnos>(this.detach_Cargas_Alumnos));
			this._Cargas_Docentes = new EntitySet<Cargas_Docentes>(new Action<Cargas_Docentes>(this.attach_Cargas_Docentes), new Action<Cargas_Docentes>(this.detach_Cargas_Docentes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Materia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Materia
		{
			get
			{
				return this._ID_Materia;
			}
			set
			{
				if ((this._ID_Materia != value))
				{
					this.OnID_MateriaChanging(value);
					this.SendPropertyChanging();
					this._ID_Materia = value;
					this.SendPropertyChanged("ID_Materia");
					this.OnID_MateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Materias_Cargas_Alumnos", Storage="_Cargas_Alumnos", ThisKey="ID_Materia", OtherKey="Materia")]
		public EntitySet<Cargas_Alumnos> Cargas_Alumnos
		{
			get
			{
				return this._Cargas_Alumnos;
			}
			set
			{
				this._Cargas_Alumnos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Materias_Cargas_Docentes", Storage="_Cargas_Docentes", ThisKey="ID_Materia", OtherKey="Materia")]
		public EntitySet<Cargas_Docentes> Cargas_Docentes
		{
			get
			{
				return this._Cargas_Docentes;
			}
			set
			{
				this._Cargas_Docentes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cargas_Alumnos(Cargas_Alumnos entity)
		{
			this.SendPropertyChanging();
			entity.Materias = this;
		}
		
		private void detach_Cargas_Alumnos(Cargas_Alumnos entity)
		{
			this.SendPropertyChanging();
			entity.Materias = null;
		}
		
		private void attach_Cargas_Docentes(Cargas_Docentes entity)
		{
			this.SendPropertyChanging();
			entity.Materias = this;
		}
		
		private void detach_Cargas_Docentes(Cargas_Docentes entity)
		{
			this.SendPropertyChanging();
			entity.Materias = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Usuarios del sistema]")]
	public partial class Usuarios_del_sistema : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Usuario;
		
		private string _Nombre;
		
		private string _Contraseña;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_UsuarioChanging(int value);
    partial void OnID_UsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    #endregion
		
		public Usuarios_del_sistema()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Usuario
		{
			get
			{
				return this._ID_Usuario;
			}
			set
			{
				if ((this._ID_Usuario != value))
				{
					this.OnID_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._ID_Usuario = value;
					this.SendPropertyChanged("ID_Usuario");
					this.OnID_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class MostrarCargasAlumnosResult
	{
		
		private int _ID;
		
		private string _Alumno;
		
		private string _Carrera;
		
		private string _Materia;
		
		private string _Profesor;
		
		public MostrarCargasAlumnosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alumno", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Alumno
		{
			get
			{
				return this._Alumno;
			}
			set
			{
				if ((this._Alumno != value))
				{
					this._Alumno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this._Carrera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materia", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Materia
		{
			get
			{
				return this._Materia;
			}
			set
			{
				if ((this._Materia != value))
				{
					this._Materia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesor", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Profesor
		{
			get
			{
				return this._Profesor;
			}
			set
			{
				if ((this._Profesor != value))
				{
					this._Profesor = value;
				}
			}
		}
	}
	
	public partial class MostrarCargasDocentesResult
	{
		
		private int _ID;
		
		private string _Profesor;
		
		private string _Carrera;
		
		private string _Materia;
		
		public MostrarCargasDocentesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesor", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Profesor
		{
			get
			{
				return this._Profesor;
			}
			set
			{
				if ((this._Profesor != value))
				{
					this._Profesor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this._Carrera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materia", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Materia
		{
			get
			{
				return this._Materia;
			}
			set
			{
				if ((this._Materia != value))
				{
					this._Materia = value;
				}
			}
		}
	}
	
	public partial class LoginResult
	{
		
		private string _Usuario;
		
		private string _Contraseña;
		
		public LoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
	}
	
	public partial class LoginPassResult
	{
		
		private string _Usuario;
		
		private string _Contraseña;
		
		public LoginPassResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
	}
	
	public partial class LoginUsuarioResult
	{
		
		private string _Usuario;
		
		private string _Contraseña;
		
		public LoginUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
	}
	
	public partial class MostrarNombreCarrera_Por_IdAlumnoResult
	{
		
		private string _Nombre;
		
		public MostrarNombreCarrera_Por_IdAlumnoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class MostrarAlumnosResult
	{
		
		private int _ID;
		
		private string _Alumno;
		
		private string _Carrera;
		
		public MostrarAlumnosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alumno", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Alumno
		{
			get
			{
				return this._Alumno;
			}
			set
			{
				if ((this._Alumno != value))
				{
					this._Alumno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this._Carrera = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
